// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PapiKos.Models;

namespace PapiKos.Migrations
{
    [DbContext(typeof(PapiKosContext))]
    partial class PapiKosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("PapiKos.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alamat");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("PapiKos.Models.Kamar", b =>
                {
                    b.Property<int>("KamarId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeskripsiKamar");

                    b.Property<string>("Gambar");

                    b.Property<string>("HargaKamar");

                    b.Property<int>("KosId");

                    b.Property<string>("StatusKamar");

                    b.Property<string>("UkuranKamar");

                    b.HasKey("KamarId");

                    b.HasIndex("KosId");

                    b.ToTable("Kamar");
                });

            modelBuilder.Entity("PapiKos.Models.Kos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alamat");

                    b.Property<string>("DeskripsiTambahan");

                    b.Property<int>("JumlahKamar");

                    b.Property<string>("NamaKos");

                    b.Property<int?>("OwnerId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Kos");
                });

            modelBuilder.Entity("PapiKos.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Nama");

                    b.Property<string>("NomorTelephone");

                    b.HasKey("Id");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("PapiKos.Models.Kamar", b =>
                {
                    b.HasOne("PapiKos.Models.Kos", "Kos")
                        .WithMany("Kamars")
                        .HasForeignKey("KosId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PapiKos.Models.Kos", b =>
                {
                    b.HasOne("PapiKos.Models.Owner", "Owner")
                        .WithMany("Kos")
                        .HasForeignKey("OwnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
